apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-init-cosmotech-asset-investment-planning
  namespace: ${NAMESPACE}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: postgresql-init-cosmotech-asset-investment-planning
          image: ${REGISTRY}/${POSTGRESQL_IMAGE_NAME}:${POSTGRESQL_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              export PGPASSWORD='${DB_POSTGRES_PASSWORD}'
              export PGHOST='${DB_HOST}'
              export PGPORT='${DB_PORT}'

              DB_NAME='${DB_NAME}'
              SCHEMA_NAME='${DB_SCHEMA_NAME}'
              ADMIN_USER='${DB_ADMIN_USERNAME}'
              ADMIN_PASS='${DB_ADMIN_PASSWORD}'

              # Database
              if ! psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
                echo "Creating database $DB_NAME..."
                psql -U postgres -c "CREATE ROLE $ADMIN_USER WITH LOGIN PASSWORD '$ADMIN_PASS' CREATEDB;"
                psql -U postgres -c "CREATE DATABASE $DB_NAME WITH OWNER $ADMIN_USER;"
              else
                echo "Database $DB_NAME already exists, skipping."
              fi

              # Schema
              if ! psql -U postgres -tAc "SELECT 1 FROM information_schema.schemata WHERE schema_name = '$SCHEMA_NAME'" | grep -q 1; then
                echo "Creating schema $SCHEMA_NAME in database $DB_NAME..."
                psql -U postgres -d $DB_NAME -c "CREATE SCHEMA IF NOT EXISTS $SCHEMA_NAME AUTHORIZATION $ADMIN_USER;"
              else
                echo "Schema $SCHEMA_NAME already exists in database $DB_NAME. Skipping creation."
              fi
      nodeSelector:
        "cosmotech.com/tier": services
      tolerations:
        - key: "vendor"
          operator: "Equal"
          value: "cosmotech"
          effect: "NoSchedule"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ${REGISTRY_AUTH_SECRET}
