name: ${NAMESPACE}-api

serviceAccount:
  create: true

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: "${CLUSTER_DOMAIN}"
      paths:
        - path: /${NAMESPACE}/api
          pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: traefik
  tls:
    enabled: true
    secretName: "letsencrypt-prod-${NAMESPACE}"
    hosts:
      - "${CLUSTER_DOMAIN}"

# ingress:
#   enabled: true
#   className: nginx
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod-tenant-aip-portfolio
#     nginx.org/client-max-body-size: "0"
#   hosts:
#     - host: aks-dev-aip-portfolio.azure.platform.cosmotech.com
#       paths:
#         - path: /api/demo
#           pathType: ImplementationSpecific
#   tls:
#     enabled: true
#     hosts:
#       - aks-dev-aip-portfolio.azure.platform.cosmotech.com
#     secretName: letsencrypt-prod


image:
  repository: ${REGISTRY}/${COSMOTECH_ASSET_INVESTMENT_PLANNING_API_IMAGE_NAME}
  tag: ${COSMOTECH_ASSET_INVESTMENT_PLANNING_API_IMAGE_TAG}
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ${REGISTRY_AUTH_SECRET}

replicaCount: 1

autoscalling:
  enabled: false

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

tolerations:
  - effect: NoSchedule
    key: vendor
    operator: Equal
    value: cosmotech

resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 1Gi

nodeSelector:
  cosmotech.com/tier: services

extraEnvVars:
  - name: CSM_API_URL
    value: cosmotech-api-${NAMESPACE}.${NAMESPACE}.svc.cluster.local:8080

persistence:
  enabled: false

database:
  reset: false

postgres:
  enabled: true
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  database: "${DB_NAME}"
  username: "${DB_ADMIN_USERNAME}"
  password: "${DB_ADMIN_PASSWORD}"
  schema: "${DB_SCHEMA_NAME}"

apiConfig:
  corsOrigin:
    - https://${CLUSTER_DOMAIN}/${NAMESPACE}/api
  dataDir: /data
  keycloakRealm: https://${CLUSTER_DOMAIN}/keycloak/realms/${NAMESPACE}
  rootUri: /${NAMESPACE}/api

alembic:
  script_location: cosmotech/aip/migrations

webhookRestart:
  enabled: false
