name: ${NAMESPACE}-api

serviceAccount:
  create: true

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: "${CLUSTER_DOMAIN}"
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: traefik
  tls:
    enabled: true
    secretName: "letsencrypt-prod-${NAMESPACE}"
    hosts:
      - "${CLUSTER_DOMAIN}"

image:
  repository: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}
  tag: ${IMAGE_TAG}
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ${IMAGE_REGISTRY_AUTH_SECRET}

replicaCount: 1

autoscalling:
  enabled: false

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

tolerations:
  - effect: NoSchedule
    key: vendor
    operator: Equal
    value: cosmotech

resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 1Gi

nodeSelector:
  cosmotech.com/tier: services

extraEnvVars:
  - name: CSM_API_URL
    value: cosmotech-api-${NAMESPACE}.${NAMESPACE}.svc.cluster.local:8080

persistence:
  enabled: false

database:
  reset: false

postgres:
  enabled: true
  host: "${POSTGRESQL_HOST}"
  port: "${POSTGRESQL_PORT}"
  database: "${POSTGRESQL_DATABASE}"
  username: "${POSTGRESQL_USERNAME}"
  password: "${POSTGRESQL_PASSWORD}"
  schema: "cosmotech_asset_investment_planning"

apiConfig:
  corsOrigin:
    - https://${CLUSTER_DOMAIN}/${NAMESPACE}/api
  dataDir: /data
  keycloakRealm: https://${CLUSTER_DOMAIN}/keycloak/realms/${NAMESPACE}
  rootUri: ${NAMESPACE}/api

alembic:
  script_location: cosmotech/aip/migrations

webhookRestart:
  enabled: false
