replicaCount: 1
image:
  repository: ghcr.io/cosmo-tech/cosmotech-api
  pullPolicy: IfNotPresent
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
api:
  servletContextPath: /
  version: api
  multiTenant: true
  serviceMonitor:
    name: cosmotech-api-${NAMESPACE}
    enabled: true
    namespace: ${NAMESPACE_MONITORING}
  tlsTruststore:
    enabled: false
argo:
  imageCredentials:
    registry: ${REGISTRY_URL}
    username: ${REGISTRY_USERNAME}
    password: ${REGISTRY_PASSWORD}
# Note : This is a comment but is kept for future use if more logging information is needed
# logging:
#     level:
#       com.cosmotech: DEBUG
#       web: WARN
#       org.springframework: WARN
#       com.redis: WARN
# server:
#     error:
#       include-stacktrace: always
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-${NAMESPACE}
  hosts:
    - host: ${CLUSTER_DOMAIN}
  tls:
    - secretName: letsencrypt-prod-${NAMESPACE}
      hosts:
        - "${CLUSTER_DOMAIN}"
resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1Gi
nodeSelector:
  cosmotech.com/tier: services
tolerations:
- key: vendor
  operator: Equal
  value: cosmotech
  effect: NoSchedule
config:
  # Note : keep this comment it is for customer configuration by default 50MB
  # spring:
  #   servlet:
  #     multipart:
  #       max-file-size: 1MB
  #       max-request-size: 10MB
  csm:
    platform:
      containerRegistry:
        scheme: https
        host: ${REGISTRY_URL}
        username: ${REGISTRY_USERNAME}
        password: ${REGISTRY_PASSWORD}
      identityProvider:
        audience: account
        code: keycloak
        serverBaseUrl: https://${CLUSTER_DOMAIN}/keycloak
        authorizationUrl: https://${CLUSTER_DOMAIN}/keycloak/realms/${NAMESPACE}/protocol/openid-connect/auth
        tokenUrl: https://${CLUSTER_DOMAIN}/keycloak/realms/${NAMESPACE}/protocol/openid-connect/token
        defaultScopes:
          openid: "OpenId Scope"
        identity:
          clientId: ${KEYCLOAK_CLIENT_ID}
          clientSecret: ${KEYCLOAK_CLIENT_PASSWORD}
          tenantId: ${NAMESPACE}
      namespace: ${NAMESPACE}
      argo:
        base-uri: http://argo-workflows-server.${NAMESPACE}.svc.cluster.local:2746
        workflows:
          namespace: ${NAMESPACE}
          service-account-name: argo-workflows
          requests:
            storage: 20Gi
      s3:
        endpointUrl: ${S3_ENDPOINT}
        bucketName: ${S3_BUCKET}
        accessKeyId: ${S3_USERNAME}
        secretAccessKey: ${S3_PASSWORD}
      authorization:
        allowed-tenants: ${NAMESPACE}
      databases:
        resources:
          host: redis-master.${NAMESPACE}.svc.cluster.local
          port: ${REDIS_PORT}
          username: default
          password: ${REDIS_PASSWORD}
        data:
          host: ${POSTGRESQL_DATABASE_HOST}
          port: 5432
          database: ${POSTGRESQL_DATABASE_NAME}
          reader:
            username: ${POSTGRESQL_READER_USERNAME}
            password: ${POSTGRESQL_READER_PASSWORD}
          writer:
            username: ${POSTGRESQL_WRITER_USERNAME}
            password: ${POSTGRESQL_WRITER_PASSWORD}
          admin:
            username: ${POSTGRESQL_ADMIN_USERNAME}
            password: ${POSTGRESQL_ADMIN_PASSWORD}
      # Note : keep this comment it is for customer configuration
      # upload:
      #   authorized-mime-types:
      #     workspaces:
      #       - application/zip
      #       - application/xml
      #       - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      #       - application/x-tika-ooxml
      #       - text/csv
      #       - text/plain
      #       - text/x-yaml
      #       - application/json
      #       - application/vnd.apache.parquet
      #     datasets:
      #       - application/zip
      #       - application/xml
      #       - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      #       - application/x-tika-ooxml
      #       - text/csv
      #       - text/plain
      #       - text/x-yaml
      #       - application/json
      #       - application/vnd.apache.parquet