{
 "title": "${DASHBOARD_TITLE}",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "organization", "label": "Organization", "query": "TS.QUERYINDEX qualifier=total" },
   { "name": "workspace", "label": "Workspace", "query": "TS.QUERYINDEX qualifier=total" }
  ]
 },
 "panels": [
  { "title": "Scenarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(phase)\nFROM argo_archived_workflows\nWHERE phase = 'Error'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() AND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(phase)\nFROM argo_archived_workflows\nWHERE phase = 'Succeeded'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() AND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "eval \"return #redis.call('keys', 'ts2:metric:cosmotech:API:*:call')\" 0",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Avg Successful Scenario Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(EXTRACT(EPOCH FROM (finishedat - startedat)) / 3600.0)\nFROM argo_archived_workflows\nWHERE phase = 'Succeeded'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom()\nAND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Total Successful Scenario Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(EXTRACT(EPOCH FROM (finishedat - startedat)) / 3600.0)\nFROM argo_archived_workflows\nWHERE phase = 'Succeeded'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom()\nAND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Total Runs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM argo_archived_workflows\nWHERE ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() AND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Runs by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT phase, COUNT(*)\nFROM argo_archived_workflows\nWHERE ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() AND finishedat < $__timeTo()\nGROUP BY phase"
    }
   ]
  },
  {
   "title": "Avg Failed Scenario Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(EXTRACT(EPOCH FROM (finishedat - startedat)) / 3600.0)\nFROM argo_archived_workflows\nWHERE phase = 'Failed'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom()\nAND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Total Failed Scenario Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(EXTRACT(EPOCH FROM (finishedat - startedat)) / 3600.0)\nFROM argo_archived_workflows\nWHERE phase = 'Failed'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom()\nAND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(phase)\nFROM argo_archived_workflows\nWHERE phase = 'Failed'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() AND finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Runs Started per Day",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), date_trunc('day', startedat)\nFROM argo_archived_workflows\nWHERE ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND name LIKE 'workflow-sr%'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() AND finishedat < $__timeTo()\nGROUP BY date_trunc('day', startedat)"
    }
   ]
  }
 ]
}