api:
  servletContextPath: /
  version: api
  multiTenant: true
  serviceMonitor:
    name: cosmotech-api-${NAMESPACE}
    enabled: true
    namespace: ${NAMESPACE_MONITORING}
  tlsTruststore:
    enabled: false

argo:
  imageCredentials:
    registry: ${SIMU_REGISTRY_URL}
    username: ${SIMU_REGISTRY_USERNAME}
    password: ${SIMU_REGISTRY_PASSWORD}

config:
  csm:
    platform:
      namespace: ${NAMESPACE}
      authorization:
        allowed-tenants: ${NAMESPACE}
      containerRegistry:
        scheme: https
        host: ${SIMU_REGISTRY_URL}
        username: ${SIMU_REGISTRY_USERNAME}
        password: ${SIMU_REGISTRY_PASSWORD}
      identityProvider:
        audience: account
        code: keycloak
        serverBaseUrl: https://${CLUSTER_DOMAIN}/keycloak
        authorizationUrl: https://${CLUSTER_DOMAIN}/keycloak/realms/${NAMESPACE}/protocol/openid-connect/auth
        tokenUrl: https://${CLUSTER_DOMAIN}/keycloak/realms/${NAMESPACE}/protocol/openid-connect/token
        defaultScopes:
          openid: "OpenId Scope"
        identity:
          clientId: ${KEYCLOAK_CLIENT_ID}
          clientSecret: ${KEYCLOAK_CLIENT_PASSWORD}
          tenantId: ${NAMESPACE}
      argo:
        base-uri: http://argo-workflows-server.${NAMESPACE}.svc.cluster.local:2746
        workflows:
          namespace: ${NAMESPACE}
          service-account-name: argo-workflows
          requests:
            storage: 20Gi
      s3:
        endpointUrl: ${S3_ENDPOINT}
        bucketName: ${S3_BUCKET}
        accessKeyId: ${S3_USERNAME}
        secretAccessKey: ${S3_PASSWORD}
      databases:
        resources:
          host: redis-master.${NAMESPACE}.svc.cluster.local
          port: ${REDIS_PORT}
          username: default
          password: ${REDIS_PASSWORD}
        data:
          host: ${POSTGRESQL_DATABASE_HOST}
          port: 5432
          database: ${POSTGRESQL_DATABASE_NAME}
          reader:
            username: ${POSTGRESQL_READER_USERNAME}
            password: ${POSTGRESQL_READER_PASSWORD}
          writer:
            username: ${POSTGRESQL_WRITER_USERNAME}
            password: ${POSTGRESQL_WRITER_PASSWORD}
          admin:
            username: ${POSTGRESQL_ADMIN_USERNAME}
            password: ${POSTGRESQL_ADMIN_PASSWORD}

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-${NAMESPACE}
  hosts:
    - host: ${CLUSTER_DOMAIN}
  tls:
    - secretName: letsencrypt-prod-${NAMESPACE}
      hosts:
        - "${CLUSTER_DOMAIN}"

replicaCount: 1

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1Gi

nodeSelector:
  cosmotech.com/tier: services

tolerations:
- key: vendor
  operator: Equal
  value: cosmotech
  effect: NoSchedule

image:
  repository: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}
  tag: ${IMAGE_TAG}
  pullPolicy: IfNotPresent
