apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-init-cosmotechapi
  namespace: ${namespace}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: postgresql-init-cosmotechapi
          image: postgres:17-trixie
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              export PGPASSWORD='${postgres_password}'
              export PGHOST='${db_host}'
              export PGPORT='${db_port}'

              DB_NAME='${cosmotechapi_database}'
              ADMIN_USER='${cosmotechapi_admin_username}'
              ADMIN_PASS='${cosmotechapi_admin_password}'
              WRITER_USER='${cosmotechapi_writer_username}'
              WRITER_PASS='${cosmotechapi_writer_password}'
              READER_USER='${cosmotechapi_reader_username}'
              READER_PASS='${cosmotechapi_reader_password}'

              if ! psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
                echo "Creating Cosmo Tech API database..."
                psql -U postgres -c "CREATE ROLE $ADMIN_USER WITH LOGIN PASSWORD '$ADMIN_PASS' CREATEDB;"
                psql -U postgres -c "CREATE ROLE $WRITER_USER WITH LOGIN PASSWORD '$WRITER_PASS';"
                psql -U postgres -c "CREATE ROLE $READER_USER WITH LOGIN PASSWORD '$READER_PASS';"
                psql -U postgres -c "GRANT $WRITER_USER TO $ADMIN_USER;"
                psql -U postgres -c "GRANT $READER_USER TO $ADMIN_USER;"
                psql -U postgres -c "CREATE DATABASE $DB_NAME WITH OWNER $ADMIN_USER;"

                export PGPASSWORD="$ADMIN_PASS"
                psql -U $ADMIN_USER -d $DB_NAME -c "CREATE SCHEMA inputs AUTHORIZATION $WRITER_USER;"
                psql -U $ADMIN_USER -d $DB_NAME -c "CREATE SCHEMA outputs AUTHORIZATION $WRITER_USER;"
                psql -U $ADMIN_USER -d $DB_NAME -c "GRANT USAGE ON SCHEMA inputs TO $READER_USER;"
                psql -U $ADMIN_USER -d $DB_NAME -c "GRANT USAGE ON SCHEMA outputs TO $READER_USER;"
              else
                echo "Database $DB_NAME already exists, skipping."
              fi
      nodeSelector:
        "cosmotech.com/tier": services
      tolerations:
        - key: "vendor"
          operator: "Equal"
          value: "cosmotech"
          effect: "NoSchedule"
      dnsPolicy: ClusterFirst
