name: "Quality checks"
run-name: "[linter] ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on:
  push:
    branches:
      - 'ci/*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-fmt:
    name: "Terraform fmt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

  tflint:
    name: "TFLint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: TFLint run
        run: tflint --recursive --config=${{ github.workspace }}/.github/tflint.hcl